-- test data for the database

INSERT INTO "CHANNEL" VALUES ('Server Team', NULL) ON CONFLICT (CHANNELID) DO NOTHING;
INSERT INTO "CHANNEL" VALUES ('Client Team', NULL) ON CONFLICT (CHANNELID) DO NOTHING;
INSERT INTO "CHANNEL" VALUES ('Software Eng. Group', NULL) ON CONFLICT (CHANNELID) DO NOTHING;
