-- Look into using Python module "Psycopg2" for working with
-- postgreSQL database.

CREATE TABLE IF NOT EXISTS "USER" (
    USERID      VARCHAR(20) PRIMARY KEY,
    PASSWORD    VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS "CHANNEL" (
    CHANNELID   VARCHAR(40) PRIMARY KEY,
    ADMIN       VARCHAR(20) REFERENCES "USER" (USERID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "CHANNELS_JOINED" (
    USERID      VARCHAR(20),
    CHANNELID   VARCHAR(20),
    PRIMARY KEY (USERID, CHANNELID),
    FOREIGN KEY (USERID) REFERENCES "USER" (USERID) ON DELETE CASCADE ON UPDATE CASCADE
);
