-- Look into using Python module "Psycopg2" for working with
-- postgreSQL database.

CREATE TABLE IF NOT EXISTS "USER" (
    USERID      VARCHAR(20) PRIMARY KEY,
    PASSWORD    VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS "CHANNEL" (
    CHANNELID   VARCHAR(40) PRIMARY KEY,
    ADMIN       VARCHAR(20) REFERENCES "USER" (USERID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "CHANNELS_JOINED" (
    USERID      VARCHAR(20),
    CHANNELID   VARCHAR(20),
    PRIMARY KEY (USERID, CHANNELID),
    FOREIGN KEY (USERID) REFERENCES "USER" (USERID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "IS_CONNECTED_TO" (
    USERID      VARCHAR(20),
    CHANNELID   VARCHAR(40),
    MESSAGEID   SERIAL,
    MESSAGE     VARCHAR(500) NOT NULL,
    TIME_OF     TIMESTAMP NOT NULL,
    PRIMARY KEY (USERID, CHANNELID, MESSAGEID),
    FOREIGN KEY (USERID, CHANNELID) REFERENCES "CHANNELS_JOINED" (USERID, CHANNELID) ON DELETE CASCADE ON UPDATE CASCADE
);
